#! /bin/bash
swallow-mcsc.py mcmain_prim.xc blur_print.c blur.xc Power_Measure_Lib.xc Swallow-sobel.xc matrixmul.xc Swallow-prim-checks.c Swallow-wait.xc Swallow-helpers.xc Swallow-nOS_asm.s Swallow-nOS_client.xc Swallow-nOS_initialFunctions.c Swallow-nOS.xc Swallow-prim.xc -O3 -o prim.sgb
