#! /bin/bash
swallow-mcsc.py mcmain_prim.xc blur.xc Power_Measure_Lib.xc Swallow-sobel.xc matrixmul.xc Swallow-wait.xc Swallow-helpers.xc Swallow-nOS_asm.s Swallow-nOS_client.xc Swallow-nOS_initialFunctions.c Swallow-nOS.xc Swallow-prim.xc 	Swallow-prim-checks.c  -O3 -o prim.sgb
